server:
  port: 8080

spring:
  application:
    name: apigateway

  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      default-filters:
        - SaveSession
      redis:
        enabled: true

      routes:
        - id: cache_response_body_route
          uri: https://httpbin.org
          predicates:
            - Path=/cache/get/**
          filters:
            - StripPrefix=1
            - name: LocalResponseCache
              args:
                ttl: 10s
                size: 20MB

        - id: cache_request_body_route
          uri: https://httpbin.org
          predicates:
            - Path=/cache/post/**
          filters:
            - StripPrefix=1
            - name: CacheRequestBody
              args:
                bodyClass: java.lang.String

        - id: size_route
          uri: https://httpbin.org
          predicates:
            - Path=/anything
          filters:
            - name: RequestSize
              args:
                maxSize: 5000000

    circuitbreaker:
      resilience4j:
        configs:
          default:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 10s
        instances:
          myCircuitBreaker:
            baseConfig: default

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
